[project]
name = "airflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "2100031074@kluniversity.in", email = "121864410+Jaswanth2100031074@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
airflow = "airflow:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
